CREATE ROLE web_anon NOLOGIN;
GRANT web_anon TO apidbuser;

CREATE ROLE web_user NOLOGIN;
GRANT USAGE ON SCHEMA public TO web_user;
GRANT web_user TO apidbuser;

CREATE ROLE web_admin NOLOGIN;
GRANT USAGE ON SCHEMA public TO web_admin;
GRANT web_admin TO apidbuser;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO web_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, UPDATE, INSERT ON TABLES TO web_user;
